steps:
  - command: .buildkite/scripts/pipelines/security_solution_quality_gate/security_solution_cypress/mki_security_solution_cypress.sh cypress:run:qa:serverless:explore
    label: 'Serverless MKI QA Explore - Security Solution Cypress Tests'
    agents:
      queue: n2-4-spot
    # TODO : Revise the timeout when the pipeline will be officially integrated with the quality gate.
    timeout_in_minutes: 300
    parallelism: 4
    retry:
      automatic:
        - exit_status: '*'
          limit: 1