steps:
  - command: .buildkite/scripts/steps/functional/defend_workflows_serverless.sh
    label: 'Defend Workflows Cypress Tests on Serverless'
    agents:
      queue: n2-4-virt
    timeout_in_minutes: 300
    parallelism: 6
    retry:
      automatic:
        - exit_status: '*'
          limit: 1