steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

#  - command: .buildkite/scripts/steps/test/pick_test_group_run_order.sh
#    label: 'Pick Test Group Run Order'
#    agents:
#      queue: kibana-default
#    env:
#      FTR_CONFIGS_DEPS: ''
#      LIMIT_CONFIG_TYPE: 'unit,integration'
#      JEST_UNIT_SCRIPT: '.buildkite/scripts/steps/code_coverage/jest.sh'
#      JEST_INTEGRATION_SCRIPT: '.buildkite/scripts/steps/code_coverage/jest_integration.sh'
#
#  - command: .buildkite/scripts/steps/code_coverage/ingest.sh
#    label: 'Merge and Ingest'
#    agents:
#      queue: n2-4-spot
#    depends_on:
#      - jest
#      - jest-integration
#    timeout_in_minutes: 30
#    key: ingest

  - command: .buildkite/scripts/steps/nodejs_std_test_runner/node_test.sh
    label: 'Playing with new NodeJS Test Runner'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 30

  - command: node --test packages/kbn-test/new_test_runner --test-reporter tap
    label: 'Use TAP Reporter'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 30

  - command: .buildkite/scripts/steps/nodejs_std_test_runner/custom_reporter.sh
    label: 'Use NodeJS v20 to play with custom reporter'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 30
