steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      queue: kibana-default

  - wait

#  - command: .buildkite/scripts/steps/test/pick_test_group_run_order.sh
#    label: 'Pick Test Group Run Order'
#    agents:
#      queue: kibana-default
#    env:
#      FTR_CONFIGS_DEPS: ''
#      LIMIT_CONFIG_TYPE: 'unit,integration'
#      JEST_UNIT_SCRIPT: '.buildkite/scripts/steps/code_coverage/jest.sh'
#      JEST_INTEGRATION_SCRIPT: '.buildkite/scripts/steps/code_coverage/jest_integration.sh'
#
#  - command: .buildkite/scripts/steps/code_coverage/ingest.sh
#    label: 'Merge and Ingest'
#    agents:
#      queue: n2-4-spot
#    depends_on:
#      - jest
#      - jest-integration
#    timeout_in_minutes: 30
#    key: ingest

#  - command: .buildkite/scripts/steps/nodejs_std_test_runner/node_test.sh
#    label: 'Playing with new NodeJS Test Runner'
#    agents:
#      queue: n2-4-spot
#    timeout_in_minutes: 30

  - commands:
      - .buildkite/scripts/bootstrap.sh
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.2/install.sh | bash
      - source ~/.nvm/nvm.sh
      - nvm install 20.0.0
      - node --version
      - npm --version
      - node --test packages/kbn-test/new_test_runner --test-reporter tap
      - pushd packages/kbn-test/new_test_runner
      - node --test-reporter=./lifecycle_gen.mjs --test
      - node --test-reporter tap --test ./ | ../../../node_modules/tap-junit/bin/tap-junit --output "$tgt"
      - popd
      - npx junit2json target/junit/tap.xml | jq
    label: 'Kitchen Sink'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 20

  - command: node --test packages/kbn-test/new_test_runner --test-reporter tap
    label: 'Use TAP Reporter'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 10

  - commands:
      - pushd packages/kbn-test/new_test_runner
      - node --test-reporter=./lifecycle_gen.mjs --test
      - popd
    label: 'Use Generator Fn as Custom Reporter'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 10

  - command: .buildkite/scripts/steps/nodejs_std_test_runner/junit_reporter.sh
    label: 'Use Junit Reporter'
    agents:
      queue: n2-4-spot
    timeout_in_minutes: 10
