env:
  KIBANA_BUILD_ID: 01838a56-8a4a-49d5-9025-6c769ba32d93

steps:
  - label: '👨‍🔧 Pre-Build'
    command: .buildkite/scripts/lifecycle/pre_build.sh
    agents:
      queue: kibana-default

  - wait

  - label: '💪 Performance Tests with Playwright config'
    command: .buildkite/scripts/steps/functional/performance_playwright.sh
    agents:
      queue: kb-static-ubuntu
    key: tests
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
        - exit_status: '*'
          limit: 1

  - wait: ~
    continue_on_failure: true

  - label: '🦸 Post-Build'
    command: .buildkite/scripts/lifecycle/post_build.sh
    agents:
      queue: kibana-default
