env:
  KIBANA_BUILD_ID: ''

steps:
  - label: '👨‍🔧 Pre-Build'
    command: .buildkite/scripts/lifecycle/pre_build.sh
    agents:
      queue: kibana-default

  - wait

  - label: '💪 Performance Tests with Playwright config'
    command: .buildkite/scripts/steps/functional/simple_performance.sh
    agents:
      queue: kb-static-scalability
    depends_on: build
    key: tests
    timeout_in_minutes: 60
