# This pipeline can be used to upload any tested pipeline in the Elastic-wide buildkite infrastructure to be tested

steps:
  - label: Upload tested pipeline
    command: buildkite-agent pipeline upload .buildkite/pipelines/code_coverage/daily.yml
